### ISSUE TITLE
Add an npm package

### ISSUE THREAD

**Issue by mike-ward** [shaundon/simple-notifications#3]
Pretty please...

**Comment by shaundon** [comment]
Sure - I'll get on that this week, poke me if I haven't done it by the weekend.

**Comment by shaundon** [comment]
Here you go: https://www.npmjs.com/package/simple-notifications.

Should be on v1.0.4 but NPM seems to be taking a few minutes to reflect that.

**Comment by mike-ward** [comment]
Thanks!
